<?php
return [
    [
        'id'       => 'kot-system',
        'img'      => 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&auto=format&fit=crop',
        'author'   => 'DN Team',
        'date'     => 'March 15, 2024',
        'dateISO'  => '2024-03-15',
        'category' => 'Restaurant Management',
        'title'    => 'How Indian Restaurants Can Reduce Order Errors by 80% with a Digital KOT System',
        'excerpt'  => 'Manual KOT slips cause confusion, delays and revenue loss. Discover how Indian restaurants are switching to digital kitchen display systems.',
        'readTime' => '6 min read',
        'content'  => '<h2>The Problem with Paper KOTs</h2><p>Every day, thousands of Indian restaurants lose revenue because of handwritten kitchen order tickets. A waiter scribbles an order, the chef misreads it, the wrong dish goes out, and the restaurant loses both money and reputation.</p><p>Manual order errors account for up to <strong>15% of all complaints</strong> in Indian restaurants. That is a massive, preventable problem.</p><h2>What is a Digital KOT System?</h2><p>A digital KOT system replaces paper slips with a screen in the kitchen. When a waiter takes an order on a tablet or phone, it instantly appears on the kitchen display — no handwriting, no running back and forth, no lost slips.</p><h2>Real Results from Indian Restaurants</h2><ul><li><strong>Spice Garden, Pune:</strong> Reduced order errors by 80% in the first week</li><li><strong>Biryani House, Hyderabad:</strong> Cut kitchen wait time from 18 to 11 minutes</li><li><strong>Cafe Masala, Mumbai:</strong> Increased table turnover by 25% in peak hours</li></ul><h2>How TufTable KOT Works</h2><p>TufTable sends orders from the waiter device directly to the kitchen screen the moment they are placed. Chefs mark items as in-progress or done, and the waiter gets notified automatically.</p><p><strong>Contact us:</strong> <a href="mailto:dninfopvt@gmail.com">dninfopvt@gmail.com</a> | +91 79843 23769</p>',
    ],
    [
        'id'       => 'qr-ordering',
        'img'      => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&auto=format&fit=crop',
        'author'   => 'DN Team',
        'date'     => 'February 28, 2024',
        'dateISO'  => '2024-02-28',
        'category' => 'QR Ordering',
        'title'    => 'QR Code Menu Ordering for Indian Restaurants: Complete Guide 2024',
        'excerpt'  => 'QR-based ordering is transforming how Indian restaurants serve customers. No app download needed — guests scan, order and pay from their table.',
        'readTime' => '7 min read',
        'content'  => '<h2>Why QR Ordering is Perfect for Indian Restaurants</h2><p>Indian restaurants deal with high footfall, multilingual customers and fast table turnover. QR code ordering solves all three problems at once. Customers scan a code on the table, browse your full menu with photos and prices, and place their order without waiting for a waiter.</p><h2>How It Works with TufTable</h2><ol><li>TufTable generates a QR code automatically — you print and place it on each table</li><li>Customer scans with any smartphone camera — no app download needed</li><li>They browse your menu, add items to cart and place the order</li><li>Order goes directly to the kitchen KOT screen</li></ol><h2>Benefits</h2><ul><li><strong>Reduce waiter workload by 40%</strong></li><li><strong>Increase average order value by 20%</strong> — customers browse more when they see photos</li><li><strong>Works in Hindi and English</strong></li></ul><p>Contact DN Info Solution for a demo: <a href="mailto:dninfopvt@gmail.com">dninfopvt@gmail.com</a></p>',
    ],
    [
        'id'       => 'gst-billing',
        'img'      => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&auto=format&fit=crop',
        'author'   => 'DN Team',
        'date'     => 'February 10, 2024',
        'dateISO'  => '2024-02-10',
        'category' => 'Billing & GST',
        'title'    => 'GST Billing for Restaurants in India: How to Automate and Stay Compliant',
        'excerpt'  => 'GST compliance is non-negotiable for Indian restaurants. Learn how TufTable automates GST calculation and generates compliant bills.',
        'readTime' => '8 min read',
        'content'  => '<h2>GST for Restaurants: The Basics</h2><p>Indian restaurants fall under two GST slabs: <strong>5% GST</strong> for restaurants without AC or liquor licence, and <strong>18% GST</strong> for AC restaurants or those serving alcohol. Getting this wrong means penalties.</p><h2>Common GST Mistakes</h2><ul><li>Applying wrong GST rate (5% vs 18%)</li><li>Not separating food and service charges correctly</li><li>Missing GSTIN on bills</li><li>Not filing returns on time due to manual billing errors</li></ul><h2>How TufTable Automates GST Billing</h2><p>TufTable automatically applies the correct GST rate. Every bill includes your GSTIN, itemised CGST + SGST breakdown, and digital receipt via WhatsApp or email.</p><h2>Export for Your CA</h2><p>Export all GST data in Excel format — monthly, quarterly or annually. Contact DN Info Solution: <a href="mailto:dninfopvt@gmail.com">dninfopvt@gmail.com</a> | Surat, Gujarat</p>',
    ],
    [
        'id'       => 'table-reservation',
        'img'      => 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&auto=format&fit=crop',
        'author'   => 'DN Team',
        'date'     => 'January 22, 2024',
        'dateISO'  => '2024-01-22',
        'category' => 'Table Reservations',
        'title'    => 'Online Table Booking for Indian Restaurants: Why It Is No Longer Optional',
        'excerpt'  => 'Weekend rush, wedding season, festival bookings — Indian restaurants lose lakhs every year from no-shows and walk-in chaos.',
        'readTime' => '5 min read',
        'content'  => '<h2>The Cost of Not Having Online Reservations</h2><p>During Diwali, Valentine Day or a Saturday evening, Indian restaurants face two problems: walk-in customers waiting 45 minutes for a table, and reserved tables sitting empty because of no-shows. Both cost money.</p><h2>What a Smart Reservation System Does</h2><ul><li>Customers book tables online from your website, WhatsApp or QR code</li><li>Automatic confirmation SMS/email sent to customer</li><li>Reminder sent 2 hours before booking to reduce no-shows</li><li>Tables automatically marked as reserved on the floor plan</li></ul><h2>Results</h2><ul><li><strong>60% reduction in no-shows</strong> due to automated reminders</li><li><strong>35% increase in weekend revenue</strong> from better table utilisation</li><li><strong>Zero double-bookings</strong></li></ul><p>Contact DN Info Solution: <a href="mailto:dninfopvt@gmail.com">dninfopvt@gmail.com</a></p>',
    ],
    [
        'id'       => 'sales-analytics',
        'img'      => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop',
        'author'   => 'DN Team',
        'date'     => 'January 8, 2024',
        'dateISO'  => '2024-01-08',
        'category' => 'Sales Analytics',
        'title'    => 'Top 5 Sales Reports Every Indian Restaurant Owner Must Track Daily',
        'excerpt'  => 'Most restaurant owners in India run on gut feeling. The ones growing fast run on data. Here are the 5 reports that separate profitable restaurants from struggling ones.',
        'readTime' => '6 min read',
        'content'  => '<h2>Why Data Matters for Indian Restaurants</h2><p>Most Indian restaurant owners know their busiest day is Saturday and their best dish is butter chicken. But do they know exactly how much butter chicken they sell on Saturday evenings vs Sunday afternoons? That level of detail separates a 50 lakh/year restaurant from a 1 crore/year restaurant.</p><h2>The 5 Reports You Must Track</h2><h3>1. Daily Revenue Report</h3><p>Total sales broken down by payment method (cash, UPI, card). Know exactly what came in every day.</p><h3>2. Item Sales Report</h3><p>Which dishes sold the most? Which ones are never ordered? Remove the dead weight and push your winners.</p><h3>3. Peak Hours Report</h3><p>When are your busiest 2 hours? Staff accordingly.</p><h3>4. Staff Performance Report</h3><p>Which waiter handles the most tables? Who has the highest average order value?</p><h3>5. Payment Method Report</h3><p>How much is coming via UPI vs cash vs card? This affects your cash flow planning.</p><p>Contact DN Info Solution: <a href="mailto:dninfopvt@gmail.com">dninfopvt@gmail.com</a> | +91 79843 23769 | Surat, Gujarat</p>',
    ],
];
